### ISSUE TITLE
get error "invalid memory address or nil pointer dereference" when upgrade minio operator to v4.3.2 from v4.0.6 

### ISSUE THREAD

**Issue by soulseen** [minio/operator#1011]
## Expected Behavior
upgrade minio operator to v4.3.2 from v4.0.6 success, minio-operator and minio instance works well.

## Current Behavior
upgrade minio operator to v4.3.2 get an error in minio-operator, as follows:
```
I0211 09:21:26.105917       1 main.go:75] Starting MinIO Operator
I0211 09:21:26.539586       1 main.go:142] caBundle on CRD updated
I0211 09:21:26.543138       1 main-controller.go:252] Setting up event handlers
I0211 09:21:26.545697       1 leaderelection.go:243] attempting to acquire leader lease harbor-operator-ns/minio-operator-lock...
I0211 09:21:26.565271       1 leaderelection.go:253] successfully acquired lease harbor-operator-ns/minio-operator-lock
I0211 09:21:26.565613       1 main-controller.go:464] minio-operator-67ddbdd4d8-l64xv: I've become the leader
I0211 09:21:26.565707       1 main-controller.go:379] Waiting for API to start
I0211 09:21:26.618589       1 main-controller.go:361] Starting HTTPS API server
I0211 09:21:26.619046       1 main-controller.go:383] Starting Tenant controller
I0211 09:21:26.619095       1 main-controller.go:386] Waiting for informer caches to sync
I0211 09:21:26.619121       1 main-controller.go:391] Starting workers
I0211 09:21:26.727455       1 status.go:121] Hit conflict issue, getting latest version of tenant
I0211 09:21:31.573090       1 upgrades.go:84] Upgrading v4.2.9
E0211 09:21:31.573515       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 147 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x158c020, 0x254d3c0})
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0008547f0})
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x75
panic({0x158c020, 0x254d3c0})
	runtime/panic.go:1038 +0x215
github.com/minio/operator/pkg/controller/cluster.(*Controller).upgrade429(0xb, {0x1991278, 0xc000196000}, 0xc000c00018)
	github.com/minio/operator/pkg/controller/cluster/upgrades.go:271 +0x10d
github.com/minio/operator/pkg/controller/cluster.(*Controller).checkForUpgrades(0xc000490000, {0x1991278, 0xc000196000}, 0xc000416e00)
	github.com/minio/operator/pkg/controller/cluster/upgrades.go:85 +0x8c7
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc000490000, {0xc0002c8c30, 0x2c})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:630 +0x506
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x1523ba0, 0xc0008547f0})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:557 +0x245
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc000490000)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:569 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0x0)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:509 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f1216d80c50)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x19653e0, 0xc000665620}, 0x1, 0xc0001834a0)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0xc000808e90)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc000808fd0, 0x8782a6, 0xc000aca640)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:394 +0x2dd
E0211 09:21:31.573690       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
and the current Tenant.spec like:
```
  pools:
  - name: zone-harbor
    resources: {}
    securityContext:
      fsGroup: 10000
      runAsGroup: 10000
      runAsUser: 10000
    servers: 2
```
don't have pool.SecurityContext.RunAsNonRoot config.

## Possible Solution
https://github.com/minio/operator/blob/382365919b37e390b97eaf413fd2f62b3acad060/pkg/controller/cluster/upgrades.go#L271
Need to override the case when pool.SecurityContext.RunAsNonRoot is nil

## Steps to Reproduce (for bugs)
1. deploy minio operator with version v4.0.6.
2. deploy minio Tenant
3. upgrade minio operator to v4.3.2
ref issue: https://github.com/goharbor/harbor-operator/issues/833

**Comment by soulseen** [comment]
Upgrade to v4.4.7 get an error as bellow:
```
0213 06:23:08.869400       1 main.go:71] Starting MinIO Operator
I0213 06:23:09.538020       1 main.go:150] caBundle on CRD updated
I0213 06:23:09.539564       1 main-controller.go:239] Setting up event handlers
I0213 06:23:09.540202       1 leaderelection.go:243] attempting to acquire leader lease harbor-operator-ns/minio-operator-lock...
I0213 06:23:09.586729       1 leaderelection.go:253] successfully acquired lease harbor-operator-ns/minio-operator-lock
I0213 06:23:09.587130       1 main-controller.go:450] minio-operator-6ffdb545bb-jrg2d: I've become the leader
I0213 06:23:09.588439       1 main-controller.go:365] Waiting for API to start
panic: tls: private key does not match public key

goroutine 112 [running]:
github.com/minio/operator/pkg/controller/cluster.(*Controller).generateTLSCert(0xc0004687e0)
	github.com/minio/operator/pkg/controller/cluster/operator.go:135 +0x525
github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1.1()
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:346 +0x12c
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:341 +0xb2
```

**Comment by harshavardhana** [comment]
> panic: tls: private key does not match public key
> 
> goroutine 112 [running]:
> github.com/minio/operator/pkg/controller/cluster.(*Controller).generateTLSCert(0xc0004687e0)
> 	github.com/minio/operator/pkg/controller/cluster/operator.go:135 +0x525
> github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1.1()
> 	github.com/minio/operator/pkg/controller/cluster/main-controller.go:346 +0x12c
> created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
> 	github.com/minio/operator/pkg/controller/cluster/main-controller.go:341 +0xb2

This looks like your existing TLS private cert is the wrong @soulseen you should delete `operator-tls` cert.

**Comment by soulseen** [comment]
@harshavardhana thanks for your reply, but the error about `invalid memory address or nil pointer dereference` exists yet when upgrading to v4.4.7.
```
I0213 06:43:35.660865       1 leaderelection.go:253] successfully acquired lease harbor-operator-ns/minio-operator-lock
I0213 06:43:35.660947       1 main-controller.go:450] minio-operator-6ffdb545bb-t5wxv: I've become the leader
I0213 06:43:35.661761       1 main-controller.go:365] Waiting for API to start
I0213 06:43:35.702195       1 operator.go:100] operator TLS secret not found: secrets "operator-tls" not found
W0213 06:43:35.723490       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
W0213 06:43:35.756409       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
W0213 06:43:35.788447       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
I0213 06:43:35.788577       1 csr.go:189] Start polling for certificate of csr/operator-harbor-operator-ns-csr, every 5s, timeout after 20m0s
W0213 06:43:40.794967       1 warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
I0213 06:43:40.795226       1 csr.go:232] Certificate successfully fetched, creating secret with Private key and Certificate
I0213 06:43:40.816394       1 operator.go:102] Waiting for the operator certificates to be issued waiting for Operator cert
I0213 06:43:50.823804       1 main-controller.go:347] Starting HTTPS API server
I0213 06:43:50.824147       1 main-controller.go:369] Starting Tenant controller
I0213 06:43:50.824209       1 main-controller.go:372] Waiting for informer caches to sync
I0213 06:43:50.824264       1 main-controller.go:377] Starting workers
I0213 06:43:50.846047       1 upgrades.go:83] Upgrading v4.2.0
I0213 06:43:50.855584       1 upgrades.go:103] minio-harborcluster-sample has no log secret
I0213 06:43:50.924735       1 upgrades.go:83] Upgrading v4.2.4
I0213 06:43:50.951903       1 status.go:240] Hit conflict issue, getting latest version of tenant to update version
I0213 06:43:50.988117       1 status.go:120] Hit conflict issue, getting latest version of tenant
I0213 06:43:50.988941       1 status.go:120] Hit conflict issue, getting latest version of tenant
I0213 06:43:51.007359       1 upgrades.go:83] Upgrading v4.2.8
I0213 06:43:51.435147       1 status.go:240] Hit conflict issue, getting latest version of tenant to update version
I0213 06:43:52.234499       1 status.go:120] Hit conflict issue, getting latest version of tenant
E0213 06:43:52.635029       1 main-controller.go:556] error syncing 'cluster-sample-ns/minio-harborcluster-sample': Operation cannot be fulfilled on tenants.minio.min.io "minio-harborcluster-sample": the object has been modified; please apply your changes to the latest version and try again
I0213 06:44:10.892017       1 upgrades.go:83] Upgrading v4.2.8
I0213 06:44:10.922161       1 upgrades.go:83] Upgrading v4.2.9
E0213 06:44:10.922382       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 210 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1625ba0, 0x2655df0})
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000aba400})
	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1625ba0, 0x2655df0})
	runtime/panic.go:1038 +0x215
github.com/minio/operator/pkg/controller/cluster.(*Controller).upgrade429(0xb, {0x1a515f8, 0xc000196000}, 0xc0007dff58)
	github.com/minio/operator/pkg/controller/cluster/upgrades.go:269 +0x10d
github.com/minio/operator/pkg/controller/cluster.(*Controller).checkForUpgrades(0xc0000c85a0, {0x1a515f8, 0xc000196000}, 0xc0007eae00)
	github.com/minio/operator/pkg/controller/cluster/upgrades.go:84 +0x8c7
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0000c85a0, {0xc000e24d50, 0x2c})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:616 +0x506
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x15b9860, 0xc000aba400})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:543 +0x245
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0000c85a0)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:555 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0x0)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:495 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fed9136cc78)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a26c38, {0x1a24a80, 0xc000af0000}, 0x1, 0xc0001834a0)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00078e7b0, 0x3b9aca00, 0x0, 0x0, 0x43d405)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x86600a, 0x0, 0x0)
	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:380 +0x2dd
```

**Comment by soulseen** [comment]
the operator will upgrade to v4.2.9 before v4.4.7.

**Comment by harshavardhana** [comment]
> I0213 06:44:10.892017       1 upgrades.go:83] Upgrading v4.2.8
> I0213 06:44:10.922161       1 upgrades.go:83] Upgrading v4.2.9
> E0213 06:44:10.922382       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
> goroutine 210 [running]:
> k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1625ba0, 0x2655df0})
> 	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x85
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000aba400})
> 	k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x75
> panic({0x1625ba0, 0x2655df0})
> 	runtime/panic.go:1038 +0x215
> github.com/minio/operator/pkg/controller/cluster.(*Controller).upgrade429(0xb, {0x1a515f8, 0xc000196000}, 0xc0007dff58)
> 	github.com/minio/operator/pkg/controller/cluster/upgrades.go:269 +0x10d
> github.com/minio/operator/pkg/controller/cluster.(*Controller).checkForUpgrades(0xc0000c85a0, {0x1a515f8, 0xc000196000}, 0xc0007eae00)
> 	github.com/minio/operator/pkg/controller/cluster/upgrades.go:84 +0x8c7
> github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0000c85a0, {0xc000e24d50, 0x2c})
> 	github.com/minio/operator/pkg/controller/cluster/main-controller.go:616 +0x506
> github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x15b9860, 0xc000aba400})
> 	github.com/minio/operator/pkg/controller/cluster/main-controller.go:543 +0x245
> github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0000c85a0)
> 	github.com/minio/operator/pkg/controller/cluster/main-controller.go:555 +0x62
> github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0x0)
> 	github.com/minio/operator/pkg/controller/cluster/main-controller.go:495 +0x70
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fed9136cc78)
> 	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x67
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a26c38, {0x1a24a80, 0xc000af0000}, 0x1, 0xc0001834a0)
> 	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xb6
> k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00078e7b0, 0x3b9aca00, 0x0, 0x0, 0x43d405)
> 	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x89
> k8s.io/apimachinery/pkg/util/wait.Until(0x86600a, 0x0, 0x0)
> 	k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x25
> created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
> 	github.com/minio/operator/pkg/controller/cluster/main-controller.go:380 +0x2dd

That looks strange will check
