### ISSUE TITLE
Minio operator v4.4.18 Panics while setting up proxy.

### ISSUE THREAD

**Issue by shribigb** [minio/operator#1128]
Operator Version: v4.4.18

Operator seems to be running,
```
# kubectl get pods -n minio-operator
NAME                              READY   STATUS    RESTARTS   AGE
console-6d47dc799b-2vd9h          1/1     Running   0          22m
minio-operator-6b564bc89f-hjv79   1/1     Running   0          22m
minio-operator-6b564bc89f-lxw2v   1/1     Running   0          22m
```
The logs from operator don't show any issues
```
# kubectl logs -n minio-operator deploy/minio-operator
Found 2 pods, using pod/minio-operator-6b564bc89f-hjv79
I0518 03:51:53.130759       1 main.go:70] Starting MinIO Operator
E0518 03:51:53.596952       1 main.go:148] Error updating CRD with caBundle: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "tenants.minio.min.io": the object has been modified; please apply your changes to the latest version and try again
I0518 03:51:53.596979       1 main.go:150] caBundle on CRD updated
I0518 03:51:53.597553       1 main-controller.go:239] Setting up event handlers
I0518 03:51:53.597759       1 leaderelection.go:243] attempting to acquire leader lease minio-operator/minio-operator-lock...
I0518 03:51:53.601084       1 main-controller.go:484] new leader elected: minio-operator-6b564bc89f-lxw2v
#
#
# kubectl logs  -n minio-operator minio-operator-6b564bc89f-lxw2v
I0518 03:51:53.115073       1 main.go:70] Starting MinIO Operator
I0518 03:51:53.468327       1 main.go:150] caBundle on CRD updated
I0518 03:51:53.468779       1 main-controller.go:239] Setting up event handlers
I0518 03:51:53.468910       1 leaderelection.go:243] attempting to acquire leader lease minio-operator/minio-operator-lock...
I0518 03:51:53.482787       1 leaderelection.go:253] successfully acquired lease minio-operator/minio-operator-lock
I0518 03:51:53.482879       1 main-controller.go:465] minio-operator-6b564bc89f-lxw2v: I've become the leader
I0518 03:51:53.482897       1 main-controller.go:377] Waiting for API to start
I0518 03:51:53.482907       1 main-controller.go:369] Starting HTTP Upgrade Tenant Image server
I0518 03:51:53.501077       1 main-controller.go:346] Using Kubernetes CSR Version: v1
I0518 03:51:53.546479       1 operator.go:90] operator TLS secret not found: secrets "operator-tls" not found
I0518 03:51:53.586754       1 operator.go:90] operator TLS secret not found: secrets "operator-tls" not found
I0518 03:51:53.606493       1 csr.go:191] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
I0518 03:51:58.609696       1 csr.go:217] Certificate successfully fetched, creating secret with Private key and Certificate
I0518 03:51:58.613598       1 operator.go:92] Waiting for the operator certificates to be issued waiting for Operator cert
I0518 03:52:08.618541       1 main-controller.go:350] Starting HTTPS API server
I0518 03:52:08.618721       1 main-controller.go:380] Waiting for Upgrade Server to start
I0518 03:52:08.618751       1 main-controller.go:384] Starting Tenant controller
I0518 03:52:08.618760       1 main-controller.go:387] Waiting for informer caches to sync
I0518 03:52:08.618799       1 main-controller.go:392] Starting workers
```
Setting up the proxy doesn't work
```
]# kubectl minio proxy -n minio-operator
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/minio/kubectl-minio/cmd.(*operatorProxyCmd).run(0xc000120000)
        github.com/minio/kubectl-minio/cmd/proxy.go:91 +0x597
github.com/minio/kubectl-minio/cmd.newProxyCmd.func1(0xc0001cab00, {0xc000618540, 0x2, 0x2})
        github.com/minio/kubectl-minio/cmd/proxy.go:59 +0x25
github.com/spf13/cobra.(*Command).execute(0xc0001cab00, {0xc000618500, 0x2, 0x2})
        github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x265ab20)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        github.com/minio/kubectl-minio/main.go:30 +0x97
```

**Comment by harshavardhana** [comment]
Looks like k8s v1.24 breaking change

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
EOF
```

You need the following change as well to make things work.

**Comment by shribigb** [comment]
I applied the above change and I am still getting the above error. I also deleted the minio and re-applied,
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  name: minio-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  name: minio-operator
  namespace: minio-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
---
.....
```
And still getting,
```
# kubectl minio proxy -n minio-operator
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/minio/kubectl-minio/cmd.(*operatorProxyCmd).run(0xc00026c000)
        github.com/minio/kubectl-minio/cmd/proxy.go:91 +0x597
github.com/minio/kubectl-minio/cmd.newProxyCmd.func1(0xc0001b4b00, {0xc000481b80, 0x2, 0x2})
        github.com/minio/kubectl-minio/cmd/proxy.go:59 +0x25
github.com/spf13/cobra.(*Command).execute(0xc0001b4b00, {0xc000481b40, 0x2, 0x2})
        github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x265ab20)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        github.com/minio/kubectl-minio/main.go:30 +0x97
```
