### ISSUE TITLE
minio-operator pod is in CrashLoopBackOff

### ISSUE THREAD

**Issue by balamurugana** [minio/operator#1436]
In the latest master testing in local VM running steps followed in `testings/deploy-tenant.sh` manually exhibits `minio-operator`  pod in `CrashLoopBackOff`

Below is the log
```
I0206 14:02:48.876127       1 main.go:77] Starting MinIO Operator
I0206 14:02:50.427481       1 main.go:176] caBundle on CRD updated
I0206 14:02:50.427816       1 main-controller.go:243] Setting up event handlers
I0206 14:02:50.427903       1 leaderelection.go:248] attempting to acquire leader lease minio-operator/minio-operator-lock...
I0206 14:02:50.518968       1 main-controller.go:518] minio-operator-7f7fc7c985-pw7kr: is the leader, removing any leader labels that I 'minio-operator-7f7fc7c985-7fcjz' might have
I0206 14:03:53.809814       1 leaderelection.go:258] successfully acquired lease minio-operator/minio-operator-lock
I0206 14:03:53.809961       1 main-controller.go:500] minio-operator-7f7fc7c985-7fcjz: I am the leader, applying leader labels on myself
I0206 14:03:53.810117       1 main-controller.go:409] Waiting for API to start
I0206 14:03:53.810126       1 main-controller.go:390] Starting console TLS certificate setup
I0206 14:03:53.810131       1 main-controller.go:404] Console TLS is not enabled
I0206 14:03:53.810304       1 main-controller.go:381] Starting HTTP Upgrade Tenant Image server
I0206 14:03:53.832594       1 main-controller.go:352] Using Kubernetes CSR Version: v1
I0206 14:03:53.857464       1 main-controller.go:356] Starting HTTPS API server
I0206 14:03:53.857616       1 main-controller.go:412] Waiting for Upgrade Server to start
I0206 14:03:53.857621       1 main-controller.go:415] Waiting for Console TLS
I0206 14:03:53.857625       1 main-controller.go:419] Starting Tenant controller
I0206 14:03:53.857627       1 main-controller.go:422] Waiting for informer caches to sync
I0206 14:03:53.857636       1 main-controller.go:427] Starting workers
W0206 14:03:54.883392       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
W0206 14:03:55.225636       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
I0206 14:03:55.225693       1 status.go:120] Hit conflict issue, getting latest version of tenant
W0206 14:03:55.238058       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
E0206 14:03:55.813560       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 122 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1aceb20?, 0x2d94b40})
	k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00084df80?})
	k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1aceb20, 0x2d94b40})
	runtime/panic.go:884 +0x213
github.com/minio/operator/pkg/resources/deployments.logSearchAPIEnvVars(0xc0003ff400)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:30 +0x3c
github.com/minio/operator/pkg/resources/deployments.logSearchAPIContainer(_)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:106 +0x72
github.com/minio/operator/pkg/resources/deployments.NewForLogSearchAPI(0xc0003ff400)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:176 +0xe5
github.com/minio/operator/pkg/controller/cluster.(*Controller).checkAndCreateLogSearchAPIDeployment(0xc00045cb40, {0x200d678, 0xc000058028}, 0xc0003ff400)
	github.com/minio/operator/pkg/controller/cluster/log-search.go:237 +0x275
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc00045cb40, {0xc000833128, 0x18})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:1217 +0x4c65
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x19fb0c0?, 0xc00084df80})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:605 +0x24f
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc00045cb40)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:617 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0xc0006556a0?)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:557 +0x47
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x70227b3a2274656b?, {0x1ff4ec0, 0xc000271950}, 0x1, 0xc00009c2a0)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2265707974227b2c?, 0x3b9aca00, 0x0, 0x75?, 0xc000655710?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006557d0?, 0x8de506?, 0xc000339500?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:430 +0x4ae
E0206 14:03:55.813783       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 122 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1aceb20?, 0x2d94b40})
	k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
	k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1aceb20, 0x2d94b40})
	runtime/panic.go:884 +0x213
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00084df80?})
	k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1aceb20, 0x2d94b40})
	runtime/panic.go:884 +0x213
github.com/minio/operator/pkg/resources/deployments.logSearchAPIEnvVars(0xc0003ff400)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:30 +0x3c
github.com/minio/operator/pkg/resources/deployments.logSearchAPIContainer(_)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:106 +0x72
github.com/minio/operator/pkg/resources/deployments.NewForLogSearchAPI(0xc0003ff400)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:176 +0xe5
github.com/minio/operator/pkg/controller/cluster.(*Controller).checkAndCreateLogSearchAPIDeployment(0xc00045cb40, {0x200d678, 0xc000058028}, 0xc0003ff400)
	github.com/minio/operator/pkg/controller/cluster/log-search.go:237 +0x275
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc00045cb40, {0xc000833128, 0x18})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:1217 +0x4c65
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x19fb0c0?, 0xc00084df80})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:605 +0x24f
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc00045cb40)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:617 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0xc0006556a0?)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:557 +0x47
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x70227b3a2274656b?, {0x1ff4ec0, 0xc000271950}, 0x1, 0xc00009c2a0)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2265707974227b2c?, 0x3b9aca00, 0x0, 0x75?, 0xc000655710?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006557d0?, 0x8de506?, 0xc000339500?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:430 +0x4ae
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x174175c]

goroutine 122 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
	k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1aceb20, 0x2d94b40})
	runtime/panic.go:884 +0x213
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00084df80?})
	k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1aceb20, 0x2d94b40})
	runtime/panic.go:884 +0x213
github.com/minio/operator/pkg/resources/deployments.logSearchAPIEnvVars(0xc0003ff400)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:30 +0x3c
github.com/minio/operator/pkg/resources/deployments.logSearchAPIContainer(_)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:106 +0x72
github.com/minio/operator/pkg/resources/deployments.NewForLogSearchAPI(0xc0003ff400)
	github.com/minio/operator/pkg/resources/deployments/log-search-api.go:176 +0xe5
github.com/minio/operator/pkg/controller/cluster.(*Controller).checkAndCreateLogSearchAPIDeployment(0xc00045cb40, {0x200d678, 0xc000058028}, 0xc0003ff400)
	github.com/minio/operator/pkg/controller/cluster/log-search.go:237 +0x275
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc00045cb40, {0xc000833128, 0x18})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:1217 +0x4c65
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x19fb0c0?, 0xc00084df80})
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:605 +0x24f
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc00045cb40)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:617 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0xc0006556a0?)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:557 +0x47
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x70227b3a2274656b?, {0x1ff4ec0, 0xc000271950}, 0x1, 0xc00009c2a0)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2265707974227b2c?, 0x3b9aca00, 0x0, 0x75?, 0xc000655710?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006557d0?, 0x8de506?, 0xc000339500?)
	k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:430 +0x4ae
```

## Expected Behavior

It should work normally

## Current Behavior

Crashing with stacktrace

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`): master
* Environment name and version (e.g. kubernetes v1.17.2): Kind
* Server type and version: KVM VM
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by dvaldivia** [comment]
Strange, I specifically patched this on #1428 https://github.com/minio/operator/blob/master/pkg/resources/deployments/log-search-api.go#L30

the only thing I'm not checking null for is the tenant itself, I'll try to reproduce and see what could cause this

**Comment by allanrogerr** [comment]
This does not seem to be happening on master on commit=d6191131cf10cffb29b1dffff53447f0c4de8e69 (https://github.com/minio/operator/commit/d6191131cf10cffb29b1dffff53447f0c4de8e69).

Could you test and try again please?

**Comment by allanrogerr** [comment]
Issue is not reproducible on master, now `minio-operator v5.0.10`. Closing issue.
