### ISSUE TITLE
MinIO operator pod in crashloopback when one of the API service is down

### ISSUE THREAD

**Issue by mshanmu** [minio/operator#1443]
When one of the API Services is down for whatever reason, it causes MinIO operator pods to go into crashloopback with the following error in the log,

panic: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: an error on the server ("Internal Server Error: \"/apis/metrics.k8s.io/v1beta1?timeout=32s\": the server could not find the requested resource") has prevented the request from succeeding

goroutine 225 [running]:
github.com/minio/operator/pkg/controller/cluster/certificates.GetCertificatesAPIVersion.func1()
	github.com/minio/operator/pkg/controller/cluster/certificates/csr.go:100 +0x1e5
sync.(*Once).doSlow(0x16daca0, 0x1000000000001)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/minio/operator/pkg/controller/cluster/certificates.GetCertificatesAPIVersion({0x1b18b30, 0xc00047cf20})
	github.com/minio/operator/pkg/controller/cluster/certificates/csr.go:89 +0x5e
github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1.1()
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:345 +0x4b
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:343 +0xc5

## Expected Behavior
MinIO Operator pods don't crash when some unrelated service goes down. 

## Current Behavior
When MinIO operator pods goes down, the MinIO instance goes down as well after some 30 minutes, not clear on the timing.

## Possible Solution
This issue is because of the use of discovery API to determine the Certificate version in https://github.com/minio/operator/blob/master/pkg/controller/cluster/certificates/csr.go#L82 line. The discovery API fails even if one of the API services is down. 

So, possible solution, 

1. Don't crash if the API discovery service fails, just log a warning message saying the certificate generation might be affected and continue. Use a sane default like CSRv1.

## Steps to Reproduce (for bugs)
1. Install minio-operator v4.5.5
2. Create minio tenant 
3. Scale down the metrics server, "kubectl -n kube-system scale --replicas=0 deploy/metrics-server". This is the easiest way to reproduce this problem, but, you can shut down any other API service and will see the same results.
4. Notice the minio operator pods are in crash loopback
5. After 30 minutes or so, notice the minio pods are in crash loopback as well.

## Context

1. We encountered it when we upgraded kubernetes cluster from v1.21 to v1.24.
2. Metrics server v0.3.x has incompatibility with kubernetes v1.22+, so it started failing silently
3. Started noticing operator pod restarts

## Regression
No

## Your Environment
* Version used (`minio-operator`): v4.5.5
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.24
* Server type and version:
* Operating System and version (`uname -a`): Linux
* Link to your deployment file:

**Comment by mshanmu** [comment]
Thanks @dvaldivia !!
