### ISSUE TITLE
Flink cannot connect to MINIO Tenant as S3 Persistent Store

### ISSUE THREAD

**Issue by rkcullen** [minio/operator#649]
## Expected Behavior
Flink Job Manager should be able to write it's checkpoints and savepoints to MINIO for persistence (s3://flink/checkpoints) and Flink Streaming jobs should be able to write streaming part files to a bucket on MINIO (s3://flink/part-files)

## Current Behavior

When Flink attempts to initialize a job, a certificate error is thrown trying to connect to MINIO:
`Caused by: org.apache.flink.util.FlinkRuntimeException: Failed to create checkpoint storage at checkpoint coordinator side.
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.<init>(CheckpointCoordinator.java:324)
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.<init>(CheckpointCoordinator.java:240)
	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraph.enableCheckpointing(DefaultExecutionGraph.java:448)
	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraphBuilder.buildGraph(DefaultExecutionGraphBuilder.java:311)
	at org.apache.flink.runtime.scheduler.DefaultExecutionGraphFactory.createAndRestoreExecutionGraph(DefaultExecutionGraphFactory.java:107)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:342)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:190)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:120)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:132)
	at org.apache.flink.runtime.jobmaster.DefaultSlotPoolServiceSchedulerFactory.createScheduler(DefaultSlotPoolServiceSchedulerFactory.java:110)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:340)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:317)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.internalCreateJobMasterService(DefaultJobMasterServiceFactory.java:107)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.lambda$createJobMasterService$0(DefaultJobMasterServiceFactory.java:95)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:112)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 7 more
Caused by: org.apache.hadoop.fs.s3a.AWSClientIOException: doesBucketExist on flink: com.amazonaws.SdkClientException: Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:177)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:111)
	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:260)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:317)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:256)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:231)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.verifyBucketExists(S3AFileSystem.java:372)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:308)
	at org.apache.flink.fs.s3.common.AbstractS3FileSystemFactory.create(AbstractS3FileSystemFactory.java:123)
	at org.apache.flink.core.fs.PluginFileSystemFactory.create(PluginFileSystemFactory.java:62)
	at org.apache.flink.core.fs.FileSystem.getUnguardedFileSystem(FileSystem.java:506)
	at org.apache.flink.core.fs.FileSystem.get(FileSystem.java:407)
	at org.apache.flink.core.fs.Path.getFileSystem(Path.java:274)
	at org.apache.flink.runtime.state.filesystem.FsCheckpointStorageAccess.<init>(FsCheckpointStorageAccess.java:64)
	at org.apache.flink.runtime.state.storage.FileSystemCheckpointStorage.createCheckpointStorage(FileSystemCheckpointStorage.java:323)
	at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.<init>(CheckpointCoordinator.java:321)
	... 22 more`

Disabled TLS on the MinIO tenant entirely by setting `requestAutoCert=false` in the tenant object spec and redeployed. Same exception

## Steps to Reproduce (for bugs)

1. Set the appropriate params in the flink-configs.yaml to connect to MINIO
2. From the Flink Client pod bring up a shell and add the ca.crt file to the K8s truststore: `
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
update-ca-certificates`
3. Run a flink streaming job: `./bin/flink run --detached --target kubernetes-session -Dkubernetes.cluster-id=flink-jobmanager -Dkubernetes.namespace=minio-tenant-1 ./examples/streaming/TopSpeedWindowing.jar`
4. View the logs via the flink dashboard to observe the exception

## Context

Writing required flink checkpoints and savepoints. Streaming .part files to backing store

## Your Environment

* Version used: minio-operator minio/operator:v4.0.8 minio/minio:RELEASE.2021-04-06T23-11-00Z
* Environment name and version: kubernetes v1.20.5 client, v1.21.0 server
* Server type and version: Flink:1.13.0/2 TaskManagers 1 JobManager
* Operating System and version: Linux rkcullen-Alienware-Aurora-R11 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Link to helm [chart](https://gitlab.com/cmdaa/flink-helm-chart)

**Comment by nitisht** [comment]
can you post your Flink configuration here?

**Comment by kannappanr** [comment]
@rkcullen Closing this issue. Please feel free to reach out to us, when you have the requested information.
