### ISSUE TITLE
Minio Operator v4.2.3 panics

### ISSUE THREAD

**Issue by krise86** [minio/operator#795]
operator version: 4.2.3
minio image: minio/minio:RELEASE.2021-08-25T00-41-18Z

Steps to reproduce
- install operator with kubectl minio init
- deploy new tenant with kubectl apply -f tenant.yaml -n new-tenant

Result
The operator crashes during postgres database provisioning. Tried to run `kubectl minio delete` then `kubectl minio init` with same results.

Expected
The oprator provisions the postgres database correctly

### Tenant configuration
```
spec:
  certConfig: {}
  credsSecret:
    name: minio-creds-secret
  env:
  - name: MINIO_IDENTITY_OPENID_CONFIG_URL
    value: 
  - name: MINIO_IDENTITY_OPENID_CLIENT_ID
    value: 
  - name: MINIO_IDENTITY_OPENID_SCOPES
    value: 
  - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
    value: 
  - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
    value: 
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  log:
    audit:
      diskCapacityGB: 1
    resources: {}
  mountPath: /export
  pools:
  - servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: default
    volumesPerServer: 4
  requestAutoCert: false
```

### Crash log
```
I0901 07:38:39.831257 1 main.go:73] Starting MinIO Operator
Wed, Sep 1 2021 9:38:40 am | I0901 07:38:40.407571 1 main.go:140] caBundle on CRD updated
Wed, Sep 1 2021 9:38:40 am | I0901 07:38:40.408205 1 main-controller.go:242] Setting up event handlers
Wed, Sep 1 2021 9:38:40 am | I0901 07:38:40.408282 1 main-controller.go:359] Starting Tenant controller
Wed, Sep 1 2021 9:38:40 am | I0901 07:38:40.408286 1 main-controller.go:362] Waiting for informer caches to sync
Wed, Sep 1 2021 9:38:40 am | I0901 07:38:40.444398 1 main-controller.go:342] Starting HTTPS api server
Wed, Sep 1 2021 9:38:40 am | I0901 07:38:40.509331 1 main-controller.go:367] Starting workers
Wed, Sep 1 2021 9:38:45 am | E0901 07:38:45.555677 1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Wed, Sep 1 2021 9:38:45 am | goroutine 122 [running]:
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1834020, 0x26c8970)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x86
Wed, Sep 1 2021 9:38:45 am | panic(0x1834020, 0x26c8970)
Wed, Sep 1 2021 9:38:45 am | runtime/panic.go:965 +0x1b9
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets.logDbContainer(0xc00073c380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets/log.go:106 +0x1cc
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets.NewForLogDb(0xc00073c380, 0xc0007a9980, 0x19, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets/log.go:182 +0x3e5
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).checkAndCreateLogStatefulSet(0xc0001406c0, 0x1c6fe58, 0xc0000a8000, 0xc00073c380, 0xc0007a9980, 0x19, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:1230 +0x353
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0001406c0, 0xc0002edec0, 0x22, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:1078 +0x1dcf
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1(0x17c7420, 0xc000aed000, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:448 +0x1d4
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0001406c0, 0x8)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:460 +0x82
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0xc0001406c0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:400 +0x65
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000a5ab50)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a5ab50, 0x1c38540, 0xc00029a000, 0x6170225c2c5d7d01, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0x9b
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a5ab50, 0x3b9aca00, 0x0, 0x1ae4901, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.Until(0xc000a5ab50, 0x3b9aca00, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x4d
Wed, Sep 1 2021 9:38:45 am | created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:370 +0x29f
Wed, Sep 1 2021 9:38:45 am | E0901 07:38:45.555758 1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Wed, Sep 1 2021 9:38:45 am | goroutine 122 [running]:
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1834020, 0x26c8970)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x86
Wed, Sep 1 2021 9:38:45 am | panic(0x1834020, 0x26c8970)
Wed, Sep 1 2021 9:38:45 am | runtime/panic.go:965 +0x1b9
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x109
Wed, Sep 1 2021 9:38:45 am | panic(0x1834020, 0x26c8970)
Wed, Sep 1 2021 9:38:45 am | runtime/panic.go:965 +0x1b9
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets.logDbContainer(0xc00073c380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets/log.go:106 +0x1cc
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets.NewForLogDb(0xc00073c380, 0xc0007a9980, 0x19, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets/log.go:182 +0x3e5
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).checkAndCreateLogStatefulSet(0xc0001406c0, 0x1c6fe58, 0xc0000a8000, 0xc00073c380, 0xc0007a9980, 0x19, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:1230 +0x353
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0001406c0, 0xc0002edec0, 0x22, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:1078 +0x1dcf
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1(0x17c7420, 0xc000aed000, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:448 +0x1d4
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0001406c0, 0x8)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:460 +0x82
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0xc0001406c0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:400 +0x65
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000a5ab50)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a5ab50, 0x1c38540, 0xc00029a000, 0x6170225c2c5d7d01, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0x9b
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a5ab50, 0x3b9aca00, 0x0, 0x1ae4901, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.Until(0xc000a5ab50, 0x3b9aca00, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x4d
Wed, Sep 1 2021 9:38:45 am | created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:370 +0x29f
Wed, Sep 1 2021 9:38:45 am | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Wed, Sep 1 2021 9:38:45 am | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Wed, Sep 1 2021 9:38:45 am | panic: runtime error: invalid memory address or nil pointer dereference
Wed, Sep 1 2021 9:38:45 am | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x146300c]
Wed, Sep 1 2021 9:38:45 am |  
Wed, Sep 1 2021 9:38:45 am | goroutine 122 [running]:
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x109
Wed, Sep 1 2021 9:38:45 am | panic(0x1834020, 0x26c8970)
Wed, Sep 1 2021 9:38:45 am | runtime/panic.go:965 +0x1b9
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x109
Wed, Sep 1 2021 9:38:45 am | panic(0x1834020, 0x26c8970)
Wed, Sep 1 2021 9:38:45 am | runtime/panic.go:965 +0x1b9
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets.logDbContainer(0xc00073c380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets/log.go:106 +0x1cc
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets.NewForLogDb(0xc00073c380, 0xc0007a9980, 0x19, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/resources/statefulsets/log.go:182 +0x3e5
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).checkAndCreateLogStatefulSet(0xc0001406c0, 0x1c6fe58, 0xc0000a8000, 0xc00073c380, 0xc0007a9980, 0x19, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:1230 +0x353
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0001406c0, 0xc0002edec0, 0x22, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:1078 +0x1dcf
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1(0x17c7420, 0xc000aed000, 0x0, 0x0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:448 +0x1d4
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0001406c0, 0x8)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:460 +0x82
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0xc0001406c0)
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:400 +0x65
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000a5ab50)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a5ab50, 0x1c38540, 0xc00029a000, 0x6170225c2c5d7d01, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0x9b
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a5ab50, 0x3b9aca00, 0x0, 0x1ae4901, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery/pkg/util/wait.Until(0xc000a5ab50, 0x3b9aca00, 0xc000095440)
Wed, Sep 1 2021 9:38:45 am | k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x4d
Wed, Sep 1 2021 9:38:45 am | created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start
Wed, Sep 1 2021 9:38:45 am | github.com/minio/operator/pkg/controller/cluster/main-controller.go:370 +0x29f
```

**Comment by harshavardhana** [comment]
whats your k8s version @krise86 ?

**Comment by krise86** [comment]
@harshavardhana 
k8: 1.20.7 aks

solved the issue. Had to add the following to the spec. 
Seems that log.db.image is the main issue here, maybe not picking up the default values. Now it's deployed correctly with out crash

```
log:
    db:
      image: ""
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
```
